# https://github.com/TheAustinKing

language: node_js

node_js:
  - "10.9.0"

cache: npm

before_install:
  - ls -la
  - mkdir public
  - npm install
  - ls -la
  - "npm config set spin false"
  - npm i -g now

install:
  - npm install

env:
  - NOW_TOKEN=PR3rKss66tRGuARsOl64GyW2

script:
  - npm run build
  - npm run test

deploy:
  provider: scriot
  script: bash scripts/deploy.sh
  skip_cleanup: true
